# Generated by Django 4.2.19 on 2025-02-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('color', models.CharField(default='danger', max_length=20)),
            ],
        ),
    ]
