# Generated by Django 4.2.19 on 2025-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murals', '0003_artistspotlight_insight_artwork_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistspotlight',
            old_name='week_start',
            new_name='featured_week',
        ),
        migrations.AlterField(
            model_name='artistspotlight',
            name='image',
            field=models.ImageField(upload_to='artist_spotlights/'),
        ),
    ]
